version: '3.8'

services:
  backend:
    build:
      context: ./backend
    volumes:
      - ./backend:/app
    working_dir: /app
    ports:
      - "5001:5000"
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
    ports:
      - "8081:80"
    depends_on:
      - backend
    restart: unless-stopped